# Generated by Django 5.2.8 on 2025-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('warranty', models.CharField(max_length=10)),
            ],
        ),
    ]
